const preloader=document.getElementById('preloader');
window.addEventListener('load',()=>{setTimeout(()=>{preloader.classList.add('hidden');initReveal();animateCounters()},800)});
const cursor=document.getElementById('cursor'),follower=document.getElementById('cursorFollower');
let mx=0,my=0,fx=0,fy=0;
document.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;if(cursor){cursor.style.left=mx+'px';cursor.style.top=my+'px'}});
(function loop(){fx+=(mx-fx)*.08;fy+=(my-fy)*.08;if(follower){follower.style.left=fx+'px';follower.style.top=fy+'px'}requestAnimationFrame(loop)})();
document.querySelectorAll('a,button,.tech-card,.case,.pillar').forEach(el=>{el.addEventListener('mouseenter',()=>follower&&follower.classList.add('hovering'));el.addEventListener('mouseleave',()=>follower&&follower.classList.remove('hovering'))});
const canvas=document.getElementById('particleCanvas');
if(canvas){const ctx=canvas.getContext('2d');let parts=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight}resize();addEventListener('resize',resize);
class P{constructor(){this.x=Math.random()*canvas.width;this.y=Math.random()*canvas.height;this.r=Math.random()*1.4+.4;this.vx=(Math.random()-.5)*.25;this.vy=(Math.random()-.5)*.25;this.o=Math.random()*.18+.06;this.c=Math.random()>.5?'0,61,165':'124,58,237'}update(){this.x+=this.vx;this.y+=this.vy;if(this.x<0||this.x>canvas.width)this.vx*=-1;if(this.y<0||this.y>canvas.height)this.vy*=-1}draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fillStyle=`rgba(${this.c},${this.o})`;ctx.fill()}}
function init(){parts=[];const n=Math.min(60,Math.floor(innerWidth/24));for(let i=0;i<n;i++)parts.push(new P())}init();
function conn(){for(let i=0;i<parts.length;i++)for(let j=i+1;j<parts.length;j++){const dx=parts[i].x-parts[j].x,dy=parts[i].y-parts[j].y,d=Math.hypot(dx,dy);if(d<140){ctx.beginPath();ctx.moveTo(parts[i].x,parts[i].y);ctx.lineTo(parts[j].x,parts[j].y);ctx.strokeStyle=`rgba(0,61,165,${.04*(1-d/140)})`;ctx.lineWidth=.6;ctx.stroke()}}}
(function anim(){ctx.clearRect(0,0,canvas.width,canvas.height);parts.forEach(p=>{p.update();p.draw()});conn();requestAnimationFrame(anim)})();}
const navbar=document.getElementById('navbar');
addEventListener('scroll',()=>{if(scrollY>20)navbar.classList.add('scrolled');else navbar.classList.remove('scrolled');updateActive()});
function updateActive(){const secs=document.querySelectorAll('section[id]');const links=document.querySelectorAll('.nav-link');let cur='';secs.forEach(s=>{if(scrollY>=s.offsetTop-140)cur=s.id});links.forEach(a=>{a.classList.toggle('active',a.getAttribute('href')==='#'+cur)})}
const toggle=document.getElementById('menuToggle'),mobile=document.getElementById('mobileMenu');
if(toggle){toggle.addEventListener('click',()=>{const open=mobile.classList.toggle('active');toggle.classList.toggle('active');toggle.setAttribute('aria-expanded',open);document.body.style.overflow=open?'hidden':'';mobile.setAttribute('aria-hidden',!open)});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.classList.remove('active');toggle.classList.remove('active');toggle.setAttribute('aria-expanded','false');document.body.style.overflow=''}))}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id.length>1){const t=document.querySelector(id);if(t){e.preventDefault();scrollTo({top:t.getBoundingClientRect().top+scrollY-72,behavior:'smooth'})}}}));
function animateCounters(){document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count;let cur=0;const step=target/60;function tick(){cur+=step;if(cur<target){el.textContent=Math.floor(cur);requestAnimationFrame(tick)}else el.textContent=target}const io=new IntersectionObserver(ents=>{ents.forEach(en=>{if(en.isIntersecting){tick();io.unobserve(el)}})},{threshold:.5});io.observe(el)})}
function initReveal(){const els=document.querySelectorAll('[data-reveal]');const io=new IntersectionObserver(ents=>{ents.forEach((en,i)=>{if(en.isIntersecting){setTimeout(()=>en.target.classList.add('revealed'),i*60);io.unobserve(en.target)}})},{threshold:.12,rootMargin:'0px 0px -40px 0px'});els.forEach(e=>io.observe(e))}
document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;card.style.transform=`perspective(900px) rotateX(${-y/18}deg) rotateY(${x/18}deg)`});card.addEventListener('mouseleave',()=>card.style.transform='perspective(900px) rotateX(0) rotateY(0)')});
const lightbox=document.getElementById('lightbox'),lbImg=document.getElementById('lightboxImg'),lbClose=document.getElementById('lightboxClose');
document.querySelectorAll('.gallery-item').forEach(btn=>btn.addEventListener('click',()=>{lbImg.src=btn.dataset.src;lbImg.alt=btn.querySelector('img').alt;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
function closeLb(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''}if(lbClose)lbClose.addEventListener('click',closeLb);if(lightbox)lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLb()});addEventListener('keydown',e=>{if(e.key==='Escape'&&lightbox.classList.contains('open'))closeLb()});
const form=document.getElementById('contactForm'),status=document.getElementById('formStatus');
if(form){form.addEventListener('submit',async e=>{const honey=form.querySelector('input[name="_honey"]');if(honey&&honey.value){e.preventDefault();return}const btn=form.querySelector('button[type="submit"]');const orig=btn.innerHTML;btn.disabled=true;btn.innerHTML='<span>Envoi en cours...</span>';status.textContent='';status.className='form-status';
try{const data=new FormData(form);const res=await fetch(form.action,{method:'POST',body:data,headers:{'Accept':'application/json'}});if(res.ok){status.textContent='Votre message a bien été envoyé. Merci pour votre contact.';status.className='form-status ok';form.reset();if(location.hash.includes('sent'))history.replaceState(null,'',location.pathname+'#contact')}else throw new Error();
}catch{status.textContent="Une erreur est survenue. Veuillez réessayer ou utiliser directement l'adresse email m.dababi@hotmail.com";status.className='form-status err'}
finally{btn.disabled=false;btn.innerHTML=orig;setTimeout(()=>{status.textContent='';status.className='form-status'},7000)}});
if(new URLSearchParams(location.search).get('sent')||location.hash.includes('sent')){status.textContent='Votre message a bien été envoyé. Merci pour votre contact.';status.className='form-status ok'}}
